// src/App.jsx
import "./styles/index.css";
import Navbar from "./components/Navbar";
import Hero from "./components/Hero";
import Skills from "./components/Skills";
import Projects from "./components/Projects";
import Contacts from "./components/Contacts";
function App() {
  return (
    <>
    <Navbar/>
    <Hero/>
    <Skills/>
    <Projects/>
    <Contacts/>
    </>
  );
}

export default App;

// src/App.vue
<script lang="ts">
import { defineComponent } from 'vue';
import Hero from './components/Home/Hero.vue';
import Projects from './components/Home/Projects.vue';
import Navbar from './components/General/Navbar.vue';

export default defineComponent({
  name: 'App',
  components: { Hero, Projects,Navbar },
});
</script>

<template>
  <div>
    <Navbar/>
    <Hero />
    <Projects />
  </div>
</template>

<style scoped lang="scss"></style>
